### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by gdragone1** [raminnakhli/HMM-DNN-Speech-Recognition#1] opened 2020-05-03 15:52 UTC
I don't change anything, and excute as the readme.Maybe is there the wrong hmmlearn's version?
The error as follows.
```
---- training DNN network
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
trained:  True
---- training HMM-DNN
Traceback (most recent call last):
  File "main.py", line 175, in <module>
    module.fit(np.concatenate(train_dataset_list[i]), train_len_list[i])
  File "/home/yangxu/yangyang/hmm/HMM-DNN-Speech-Recognition-master/hmm_dnn.py", line 62, in fit
    self._init(X, lengths=lengths)
  File "/home/yangxu/.local/lib/python3.6/site-packages/hmmlearn/base.py", line 547, in _init
    n_fit_scalars_per_param = self._get_n_fit_scalars_per_param()
AttributeError: 'hmm_dnn' object has no attribute '_get_n_fit_scalars_per_param'
```

**Comment by jiwidi** [comment] 2020-07-03 14:59
same here

**Comment by raminnakhli** [comment] 2020-07-03 17:05
It seems that the problem is hmmlearn version. I add the version to the requirement.txt. So, it should be fixed now.
Please let me know if you still have the problem.

**Closed as completed** 2020-07-12 19:25 UTC
Labels: bug
